### ISSUE TITLE
compiling tutorial for RPi 3

### ISSUE THREAD

**Issue by Vitalic66** [AlbrechtL/dab-rpi_raspbian_image#4]
Tried to follow instructions for RPi cross compiling but when i try to start welle-io on Pi, i get the error, that the binary file can't be opened.

I also have problems while testing the qopenwidget. I followed the insturcion and "removed" EGL/GLES libraries and added symbolic links, but when i boot to command line, qopenwidget outputs the error about missing libraries.

Is it also possible to run welle-io on x desktop of Pi?

**Comment by AlbrechtL** [comment]
Is your issue resolved?
